// Shople food price database — September 2026 snapshot
// price = standard shelf/online price. loyaltyPrice = discounted price where available.
// Replace/update this file annually; keep snapshotDate/snapshotLabel current.
const SHOPLE_DATA = {
  "snapshotDate": "2026-09-01",
  "snapshotLabel": "September 2026",
  "note": "Expanded September 2026 food price snapshot. Loyalty entries explicitly identify the card required. Some Lidl sources were live in late August immediately before the September snapshot.",
  "products": [
    {
      "id": "aldi-bananas-5",
      "retailer": "Aldi",
      "product": "Nature's Pick Bananas",
      "pack": "5 each",
      "price": 0.78,
      "category": "Fruit & veg",
      "source": "https://www.aldi.co.uk/products/fresh-food/fruit/k/1588161416978050001",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "aldi-pink-lady-6",
      "retailer": "Aldi",
      "product": "Nature's Pick Pink Lady Apples",
      "pack": "6 each",
      "price": 2.85,
      "category": "Fruit & veg",
      "source": "https://www.aldi.co.uk/product/nature-s-pick-pink-lady-apples-000000000000271500",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "aldi-mozzarella-250",
      "retailer": "Aldi",
      "product": "Emporium Grated Mozzarella",
      "pack": "250g",
      "price": 1.89,
      "category": "Chilled",
      "source": "https://www.aldi.co.uk/product/emporium-grated-mozzarella-000000000000280873",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "aldi-mature-cheddar-400",
      "retailer": "Aldi",
      "product": "Emporium British Mature Cheddar",
      "pack": "400g",
      "price": 2.45,
      "category": "Chilled",
      "source": "https://www.aldi.co.uk/products/chilled-food/cheese/k/1588161416978051004",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "aldi-milk-2l",
      "retailer": "Aldi",
      "product": "Cowbelle Filtered British Whole Milk",
      "pack": "2L",
      "price": 1.69,
      "category": "Dairy",
      "source": "https://www.aldi.co.uk/product/cowbelle-filtered-british-whole-milk-000000000000423400",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "aldi-eggs-6",
      "retailer": "Aldi",
      "product": "Merevale Free Range Eggs",
      "pack": "6 pack",
      "price": 0.99,
      "category": "Dairy",
      "source": "https://www.aldi.co.uk/product/merevale-free-range-eggs-6-pack-000000000000548465",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "aldi-butter-250",
      "retailer": "Aldi",
      "product": "Cowbelle British Salted Butter",
      "pack": "250g",
      "price": 1.85,
      "category": "Dairy",
      "source": "https://www.aldi.co.uk/product/cowbelle-british-salted-butter-250g-000000000000416554",
      "verified": "2026-09-01",
      "previousPrice": 1.99,
      "offer": true,
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "aldi-chicken-650",
      "retailer": "Aldi",
      "product": "Ashfields Chicken Breast Fillets",
      "pack": "650g",
      "price": 4.69,
      "category": "Meat",
      "source": "https://www.aldi.co.uk/product/ashfields-chicken-breast-fillets-000000000000383730",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "aldi-rice-1kg",
      "retailer": "Aldi",
      "product": "Worldwide Foods Basmati Rice",
      "pack": "1kg",
      "price": 1.79,
      "category": "Food cupboard",
      "source": "https://www.aldi.co.uk/product/worldwide-foods-basmati-rice-000000000000262344",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "aldi-macaroni-500",
      "retailer": "Aldi",
      "product": "Cucina Macaroni Pasta",
      "pack": "500g",
      "price": 0.72,
      "category": "Food cupboard",
      "source": "https://www.aldi.co.uk/product/cucina-macaroni-pasta-500g-000000000000308242",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "aldi-penne-500",
      "retailer": "Aldi",
      "product": "Cucina Penne Pasta",
      "pack": "500g",
      "price": 0.69,
      "category": "Food cupboard",
      "source": "https://www.aldi.co.uk/product/cucina-penne-pasta-500g-000000000000308638",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-milk-4pint",
      "retailer": "Tesco",
      "product": "Tesco British Semi Skimmed Milk",
      "pack": "4 pints / 2.272L",
      "price": 1.65,
      "category": "Dairy",
      "source": "https://www.tesco.com/shop/en-GB/products/254656543",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-eggs-6-medium",
      "retailer": "Tesco",
      "product": "Tesco Free Range Eggs Medium",
      "pack": "6 pack",
      "price": 1.8,
      "category": "Dairy",
      "source": "https://www.tesco.com/shop/en-GB/browse/fresh-food/milk-butter-and-eggs/eggs/free-range-eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-eggs-6-large",
      "retailer": "Tesco",
      "product": "Tesco Large Free Range Eggs",
      "pack": "6 pack",
      "price": 2.1,
      "category": "Dairy",
      "source": "https://www.tesco.com/shop/en-GB/products/250802567",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-butter-250",
      "retailer": "Tesco",
      "product": "Tesco English Salted Butter",
      "pack": "250g",
      "price": 1.85,
      "category": "Dairy",
      "source": "https://www.tesco.com/shop/en-GB/products/256542847",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-butter-block-250",
      "retailer": "Tesco",
      "product": "Tesco British Salted Block Butter",
      "pack": "250g",
      "price": 1.99,
      "category": "Dairy",
      "source": "https://www.tesco.com/shop/en-GB/products/290920510",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-cheddar-400",
      "retailer": "Tesco",
      "product": "Tesco Mature Cheddar",
      "pack": "400g",
      "price": 3.25,
      "category": "Chilled",
      "source": "https://www.tesco.com/shop/en-GB/products/305977270",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-pasta-500",
      "retailer": "Tesco",
      "product": "Tesco Fusilli Pasta",
      "pack": "500g",
      "price": 0.75,
      "category": "Food cupboard",
      "source": "https://www.tesco.com/shop/en-GB/products/254878545",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-rice-1kg",
      "retailer": "Tesco",
      "product": "Tesco Easy Cook Long Grain Rice",
      "pack": "1kg",
      "price": 1.25,
      "category": "Food cupboard",
      "source": "https://www.tesco.com/shop/en-GB/products/254877356",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-chicken-525",
      "retailer": "Tesco",
      "product": "Tesco British Chicken Breast Fillets",
      "pack": "525g",
      "price": 3.65,
      "category": "Meat",
      "source": "https://www.tesco.com/shop/en-GB/products/304401631",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-chicken-2kg",
      "retailer": "Tesco",
      "product": "Tesco British Chicken Breast Fillets",
      "pack": "2kg",
      "price": 12.85,
      "category": "Meat",
      "source": "https://www.tesco.com/shop/en-GB/products/317311429",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-bananas-5",
      "retailer": "Tesco",
      "product": "Tesco Ripe Bananas",
      "pack": "5 pack",
      "price": 0.78,
      "category": "Fruit & veg",
      "source": "https://www.tesco.com/shop/en-GB/products/266419328",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-bread-800",
      "retailer": "Tesco",
      "product": "Tesco White Sliced Batch Bread",
      "pack": "800g",
      "price": 1.4,
      "category": "Bakery",
      "source": "https://www.tesco.com/shop/en-GB/products/310098035",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "asda-milk-2l",
      "retailer": "ASDA",
      "product": "ASDA Northern Irish Semi Skimmed Milk",
      "pack": "2L",
      "price": 1.58,
      "category": "Dairy",
      "source": "https://www.asda.com/groceries/product/semi-skimmed-milk/asda-northern-irish-semi-skimmed-milk-2-litres/1799716",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "asda-butter-250",
      "retailer": "ASDA",
      "product": "ASDA British Salted Butter",
      "pack": "250g",
      "price": 1.85,
      "category": "Dairy",
      "source": "https://www.asda.com/groceries/product/block-butter/asda-british-salted-butter-250g/3580294",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "asda-bread-800",
      "retailer": "ASDA",
      "product": "Just Essentials White Bread",
      "pack": "800g",
      "price": 0.55,
      "category": "Bakery",
      "source": "https://www.asda.com/groceries/product/white-bread/just-essentials-by-asda-just-essentials-white-bread-800g/3956734",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "asda-bread-farmhouse-800",
      "retailer": "ASDA",
      "product": "Exceptional White Farmhouse Loaf",
      "pack": "800g",
      "price": 1.6,
      "category": "Bakery",
      "source": "https://www.asda.com/groceries/product/white-bread/exceptional-by-asda-white-farmhouse-loaf-800g/9137880",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "asda-hovis-800",
      "retailer": "ASDA",
      "product": "Hovis Soft White Medium",
      "pack": "800g",
      "price": 1.39,
      "category": "Bakery",
      "source": "https://www.asda.com/groceries/product/white-bread/hovis-soft-white-medium-800g/883344",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "asda-eggs-6",
      "retailer": "ASDA",
      "product": "The Lakes Free Range Eggs",
      "pack": "6 pack",
      "price": 1.78,
      "category": "Dairy",
      "source": "https://www.asda.com/groceries/product/free-range-eggs/the-lakes-free-range-egg-co-laid-with-love-6-free-range-eggs/9174494",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "asda-eggs-happy-6",
      "retailer": "ASDA",
      "product": "The Happy Egg Co Free Range Eggs",
      "pack": "6 large",
      "price": 2.83,
      "category": "Dairy",
      "source": "https://www.asda.com/groceries/product/free-range-eggs/the-happy-egg-co-free-range-eggs-6-large/2982601",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "asda-rice-1kg",
      "retailer": "ASDA",
      "product": "Just Essentials Long Grain Rice",
      "pack": "1kg",
      "price": 0.52,
      "category": "Food cupboard",
      "source": "https://www.asda.com/groceries/product/long-grain-basmati-rice/just-essentials-by-asda-just-essentials-long-grain-rice-1kg/443428",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "asda-brown-rice-1kg",
      "retailer": "ASDA",
      "product": "ASDA Easy Cook Long Grain Brown Rice",
      "pack": "1kg",
      "price": 2.64,
      "category": "Food cupboard",
      "source": "https://www.asda.com/groceries/product/long-grain-basmati-rice/asda-easy-cook-long-grain-brown-rice/9132450",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "asda-premium-butter-250",
      "retailer": "ASDA",
      "product": "Exceptional Sea Salted West Country Butter",
      "pack": "250g",
      "price": 2.9,
      "category": "Dairy",
      "source": "https://www.asda.com/groceries/product/block-butter/exceptional-by-asda-sea-salted-west-country-british-butter-250g/9114614",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "morrisons-milk-4pint",
      "retailer": "Morrisons",
      "product": "Morrisons British Semi Skimmed Milk",
      "pack": "4 pints / 2.272L",
      "price": 1.65,
      "category": "Dairy",
      "source": "https://groceries.morrisons.com/categories/fresh-foods/milk-eggs-butter/fresh-milk/semi-skimmed-milk/177269",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "morrisons-milk-2pint",
      "retailer": "Morrisons",
      "product": "Morrisons British Semi Skimmed Milk",
      "pack": "2 pints / 1.136L",
      "price": 1.2,
      "category": "Dairy",
      "source": "https://groceries.morrisons.com/categories/fresh-foods/milk-eggs-butter/fresh-milk/semi-skimmed-milk/177269",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "morrisons-eggs-medium-6",
      "retailer": "Morrisons",
      "product": "Morrisons Medium Free Range Eggs",
      "pack": "6 pack",
      "price": 1.8,
      "category": "Dairy",
      "source": "https://groceries.morrisons.com/products/morrisons-medium-free-range-eggs-6-pack/105828736",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "morrisons-eggs-large-6",
      "retailer": "Morrisons",
      "product": "Morrisons Large Free Range Eggs",
      "pack": "6 pack",
      "price": 2.1,
      "category": "Dairy",
      "source": "https://groceries.morrisons.com/products/morrisons-large-free-range-eggs-6-pack/105828461",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "morrisons-eggs-vl-6",
      "retailer": "Morrisons",
      "product": "Morrisons Very Large Free Range Eggs",
      "pack": "6 pack",
      "price": 2.4,
      "category": "Dairy",
      "source": "https://groceries.morrisons.com/products/morrisons-very-large-free-range-eggs-6-pack/105828787",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "morrisons-cheddar-400",
      "retailer": "Morrisons",
      "product": "Morrisons British Mature Cheddar",
      "pack": "400g",
      "price": 2.95,
      "category": "Chilled",
      "source": "https://groceries.morrisons.com/categories/fresh-foods/cheese/cheddar-cheese/mature-cheddar-cheese/177382",
      "verified": "2026-09-01",
      "previousPrice": 3.25,
      "offer": true,
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "morrisons-rice-1kg",
      "retailer": "Morrisons",
      "product": "Morrisons Easy Cook Long Grain Rice",
      "pack": "1kg",
      "price": 1.25,
      "category": "Food cupboard",
      "source": "https://groceries.morrisons.com/products/morrisons-easy-cook-long-grain-rice/109748952",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "morrisons-brown-rice-1kg",
      "retailer": "Morrisons",
      "product": "Morrisons Easy Cook Brown Long Grain Rice",
      "pack": "1kg",
      "price": 1.39,
      "category": "Food cupboard",
      "source": "https://groceries.morrisons.com/products/morrisons-easy-cook-brown-long-grain-rice/104552192",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "morrisons-nutella-200",
      "retailer": "Morrisons",
      "product": "Nutella Chocolate & Hazelnut Spread",
      "pack": "200g",
      "price": 2,
      "category": "Food cupboard",
      "source": "https://groceries.morrisons.com/products/nutella-chocolate-hazelnut-spread/100113942",
      "verified": "2026-09-01",
      "previousPrice": 2.35,
      "offer": true,
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "waitrose-milk-4pint",
      "retailer": "Waitrose",
      "product": "Essential British Free Range Semi-Skimmed Milk",
      "pack": "4 pints / 2.272L",
      "price": 1.75,
      "category": "Dairy",
      "source": "https://www.waitrose.com/ecom/shop/browse/groceries/everyday_value/dairy_and_eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "waitrose-milk-2pint",
      "retailer": "Waitrose",
      "product": "Essential British Free Range Semi-Skimmed Milk",
      "pack": "2 pints / 1.136L",
      "price": 1.3,
      "category": "Dairy",
      "source": "https://www.waitrose.com/ecom/shop/browse/groceries/everyday_value/dairy_and_eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "waitrose-eggs-6",
      "retailer": "Waitrose",
      "product": "Essential Free Range White Eggs",
      "pack": "6 pack",
      "price": 1.3,
      "category": "Dairy",
      "source": "https://www.waitrose.com/ecom/shop/browse/groceries/everyday_value/dairy_and_eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "waitrose-eggs-longstock-6",
      "retailer": "Waitrose",
      "product": "No.1 Longstock Gold Free Range Eggs",
      "pack": "6 pack",
      "price": 2.85,
      "category": "Dairy",
      "source": "https://www.waitrose.com/ecom/products/no1-longstock-gold-free-range-eggs/837555-791394-791395",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "waitrose-butter-250",
      "retailer": "Waitrose",
      "product": "Essential Salted Butter",
      "pack": "250g",
      "price": 2,
      "category": "Dairy",
      "source": "https://www.waitrose.com/ecom/products/essential-salted-butter/043101-21272-21273",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "waitrose-cheddar-350",
      "retailer": "Waitrose",
      "product": "Essential Mature Cheddar Cheese",
      "pack": "350g",
      "price": 2.75,
      "category": "Chilled",
      "source": "https://www.waitrose.com/ecom/shop/browse/groceries/everyday_value/dairy_and_eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "waitrose-cheddar-550",
      "retailer": "Waitrose",
      "product": "Essential Mature Cheddar Cheese",
      "pack": "550g",
      "price": 4,
      "category": "Chilled",
      "source": "https://www.waitrose.com/ecom/shop/browse/groceries/everyday_value/dairy_and_eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "waitrose-bread-800",
      "retailer": "Waitrose",
      "product": "Waitrose Soft White Toastie Thick Sliced Bread",
      "pack": "800g",
      "price": 1,
      "category": "Bakery",
      "source": "https://www.waitrose.com/ecom/shop/browse/groceries/bakery/bread/white_bread",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "waitrose-rice-brown-1kg",
      "retailer": "Waitrose",
      "product": "Waitrose Traditional Brown Basmati Aged Rice",
      "pack": "1kg",
      "price": 3.5,
      "category": "Food cupboard",
      "source": "https://www.waitrose.com/ecom/products/waitrose-traditional-brown-basmati-aged-rice/005872-2574-2575",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "waitrose-rice-wild-1kg",
      "retailer": "Waitrose",
      "product": "Waitrose Basmati & Wild Rice",
      "pack": "1kg",
      "price": 5,
      "category": "Food cupboard",
      "source": "https://www.waitrose.com/ecom/products/waitrose-basmati-wild-rice/056259-28217-28218",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "waitrose-nutella-350",
      "retailer": "Waitrose",
      "product": "Nutella Chocolate Hazelnut Spread",
      "pack": "350g",
      "price": 3.3,
      "category": "Food cupboard",
      "source": "https://www.waitrose.com/ecom/products/nutella-chocolate-hazelnut-spread/712158-741917-741918",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "waitrose-nutella-630",
      "retailer": "Waitrose",
      "product": "Nutella Chocolate Hazelnut Spread",
      "pack": "630g",
      "price": 5.5,
      "category": "Food cupboard",
      "source": "https://www.waitrose.com/ecom/products/nutella-chocolate-hazelnut-spread/837228-705772-705773",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "waitrose-nuts-400",
      "retailer": "Waitrose",
      "product": "Waitrose Mixed Nuts",
      "pack": "400g",
      "price": 6.75,
      "category": "Food cupboard",
      "source": "https://www.waitrose.com/ecom/products/waitrose-mixed-nuts/062241-31581-31582",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "waitrose-iceberg",
      "retailer": "Waitrose",
      "product": "Essential Iceberg Lettuce",
      "pack": "1 each",
      "price": 1,
      "category": "Fruit & veg",
      "source": "https://www.waitrose.com/ecom/shop/browse/groceries/waitrose_brands/essential_waitrose_and_partners",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "waitrose-cucumber",
      "retailer": "Waitrose",
      "product": "Waitrose Loose Cucumber",
      "pack": "1 each",
      "price": 1.1,
      "category": "Fruit & veg",
      "source": "https://www.waitrose.com/ecom/shop/browse/groceries/everyday_value",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-clarence-court-leghorn-6",
      "retailer": "Tesco",
      "product": "Clarence Court Traditional Leghorn Whites Free Range Eggs",
      "pack": "6 pack",
      "price": 2.85,
      "category": "Dairy",
      "source": "https://www.tesco.com/shop/en-GB/search?query=eggs",
      "verified": "2026-09-01",
      "loyaltyCard": "Tesco Clubcard",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 2.35,
      "hasLoyaltyPrice": true
    },
    {
      "id": "tesco-eggs-medium-12",
      "retailer": "Tesco",
      "product": "Tesco Medium Free Range Eggs",
      "pack": "12 pack",
      "price": 2.85,
      "category": "Dairy",
      "source": "https://www.tesco.com/shop/en-GB/search?query=eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-eggs-large-12",
      "retailer": "Tesco",
      "product": "Tesco Large Free Range Eggs",
      "pack": "12 pack",
      "price": 3.3,
      "category": "Dairy",
      "source": "https://www.tesco.com/shop/en-GB/search?query=eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-eggs-medium-6",
      "retailer": "Tesco",
      "product": "Tesco Free Range Eggs Medium",
      "pack": "6 pack",
      "price": 1.8,
      "category": "Dairy",
      "source": "https://www.tesco.com/shop/en-GB/search?query=eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-finest-maran-6",
      "retailer": "Tesco",
      "product": "Tesco Finest 6 Free Range Chestnut Maran Eggs",
      "pack": "6 pack",
      "price": 2.9,
      "category": "Dairy",
      "source": "https://www.tesco.com/shop/en-GB/search?query=eggs",
      "verified": "2026-09-01",
      "loyaltyCard": "Tesco Clubcard",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 2.6,
      "hasLoyaltyPrice": true
    },
    {
      "id": "tesco-st-ewe-rich-yolk-6",
      "retailer": "Tesco",
      "product": "St. Ewe Rich Yolk Large Free-Range Eggs",
      "pack": "6 pack",
      "price": 3.5,
      "category": "Dairy",
      "source": "https://www.tesco.com/shop/en-GB/search?query=eggs",
      "verified": "2026-09-01",
      "loyaltyCard": "Tesco Clubcard",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 2.95,
      "hasLoyaltyPrice": true
    },
    {
      "id": "tesco-eggs-very-large-6",
      "retailer": "Tesco",
      "product": "Tesco Free Range Eggs Very Large",
      "pack": "6 pack",
      "price": 2.4,
      "category": "Dairy",
      "source": "https://www.tesco.com/shop/en-GB/search?query=eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-philadelphia-protein-165",
      "retailer": "Tesco",
      "product": "Philadelphia Protein Low Fat Soft Cream Cheese",
      "pack": "165g",
      "price": 2.25,
      "category": "Chilled",
      "source": "https://www.tesco.com/shop/en-GB/search?query=cheese",
      "verified": "2026-09-01",
      "loyaltyCard": "Tesco Clubcard",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.25,
      "hasLoyaltyPrice": true
    },
    {
      "id": "tesco-babybel-6",
      "retailer": "Tesco",
      "product": "Mini Babybel Original Cheese Snacks",
      "pack": "6 x 20g",
      "price": 2.45,
      "category": "Chilled",
      "source": "https://www.tesco.com/shop/en-GB/search?query=cheese",
      "verified": "2026-09-01",
      "loyaltyCard": "Tesco Clubcard",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.5,
      "hasLoyaltyPrice": true
    },
    {
      "id": "tesco-babybel-10",
      "retailer": "Tesco",
      "product": "Mini Babybel Original Cheese Snacks",
      "pack": "10 x 20g",
      "price": 2.95,
      "category": "Chilled",
      "source": "https://www.tesco.com/shop/en-GB/search?query=cheese",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-cathedral-city-550",
      "retailer": "Tesco",
      "product": "Cathedral City Mature Cheddar Cheese",
      "pack": "550g",
      "price": 3.5,
      "category": "Chilled",
      "source": "https://www.tesco.com/shop/en-GB/search?query=cheese",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-extra-mature-cheddar-400",
      "retailer": "Tesco",
      "product": "Tesco Extra Mature Cheddar Cheese",
      "pack": "400g",
      "price": 3.25,
      "category": "Chilled",
      "source": "https://www.tesco.com/shop/en-GB/search?query=cheese",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-red-leicester-400",
      "retailer": "Tesco",
      "product": "Tesco Red Leicester Cheese",
      "pack": "400g",
      "price": 3.25,
      "category": "Chilled",
      "source": "https://www.tesco.com/shop/en-GB/search?query=cheese",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-creamfields-red-leicester-400",
      "retailer": "Tesco",
      "product": "Creamfields Red Leicester Cheese",
      "pack": "400g",
      "price": 2.45,
      "category": "Chilled",
      "source": "https://www.tesco.com/shop/en-GB/search?query=cheese",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-creamfields-soft-cheese-200",
      "retailer": "Tesco",
      "product": "Creamfields Soft Cheese",
      "pack": "200g",
      "price": 0.95,
      "category": "Chilled",
      "source": "https://www.tesco.com/shop/en-GB/search?query=cheese",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-wensleydale-cranberry-200",
      "retailer": "Tesco",
      "product": "Tesco Wensleydale Cheese with Cranberries",
      "pack": "200g",
      "price": 2.85,
      "category": "Chilled",
      "source": "https://www.tesco.com/shop/en-GB/search?query=cheese",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-cadbury-fingers-114",
      "retailer": "Tesco",
      "product": "Cadbury Dairy Milk Chocolate Fingers Biscuits",
      "pack": "114g",
      "price": 2.25,
      "category": "Treats",
      "source": "https://www.tesco.com/shop/en-GB/search?query=chocolate",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-twirl-6-129",
      "retailer": "Tesco",
      "product": "Cadbury Twirl Milk Chocolate 6pk Multipack",
      "pack": "129g",
      "price": 2.25,
      "category": "Treats",
      "source": "https://www.tesco.com/shop/en-GB/search?query=chocolate",
      "verified": "2026-09-01",
      "loyaltyCard": "Tesco Clubcard",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.75,
      "hasLoyaltyPrice": true
    },
    {
      "id": "tesco-kitkat-8-1656",
      "retailer": "Tesco",
      "product": "KitKat 2 Finger Milk Chocolate Biscuit Bars 8 Pack",
      "pack": "165.6g",
      "price": 2.2,
      "category": "Treats",
      "source": "https://www.tesco.com/shop/en-GB/search?query=chocolate",
      "verified": "2026-09-01",
      "loyaltyCard": "Tesco Clubcard",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.6,
      "hasLoyaltyPrice": true
    },
    {
      "id": "tesco-cadbury-4-134",
      "retailer": "Tesco",
      "product": "Cadbury Dairy Milk Chocolate Bar 4 Pack",
      "pack": "134g",
      "price": 2.25,
      "category": "Treats",
      "source": "https://www.tesco.com/shop/en-GB/search?query=chocolate",
      "verified": "2026-09-01",
      "loyaltyCard": "Tesco Clubcard",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.75,
      "hasLoyaltyPrice": true
    },
    {
      "id": "tesco-celebrations-500",
      "retailer": "Tesco",
      "product": "Celebrations Milk Chocolates Sharing Gift Tub",
      "pack": "500g",
      "price": 7,
      "category": "Treats",
      "source": "https://www.tesco.com/shop/en-GB/search?query=chocolate",
      "verified": "2026-09-01",
      "loyaltyCard": "Tesco Clubcard",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 3.95,
      "hasLoyaltyPrice": true
    },
    {
      "id": "tesco-mms-peanut-112",
      "retailer": "Tesco",
      "product": "M&M's Peanut Milk Chocolate Bag Pouch",
      "pack": "112g",
      "price": 2.2,
      "category": "Treats",
      "source": "https://www.tesco.com/shop/en-GB/search?query=chocolate",
      "verified": "2026-09-01",
      "loyaltyCard": "Tesco Clubcard",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.5,
      "hasLoyaltyPrice": true
    },
    {
      "id": "tesco-galaxy-minstrels-118",
      "retailer": "Tesco",
      "product": "Galaxy Minstrels Milk Chocolate Buttons Bag",
      "pack": "118g",
      "price": 1.69,
      "category": "Treats",
      "source": "https://www.tesco.com/shop/en-GB/search?query=chocolate",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-ms-mollys-milk-choc-100",
      "retailer": "Tesco",
      "product": "Ms Molly's Milk Chocolate Bar",
      "pack": "100g",
      "price": 0.59,
      "category": "Treats",
      "source": "https://www.tesco.com/shop/en-GB/search?query=chocolate",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-dark-choc-200",
      "retailer": "Tesco",
      "product": "Tesco Dark Chocolate Bar",
      "pack": "200g",
      "price": 2,
      "category": "Treats",
      "source": "https://www.tesco.com/shop/en-GB/search?query=dark+chocolate",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-finest-ecuador-100",
      "retailer": "Tesco",
      "product": "Tesco Finest Ecuador Dark Chocolate 75%",
      "pack": "100g",
      "price": 2.4,
      "category": "Treats",
      "source": "https://www.tesco.com/shop/en-GB/search?query=dark+chocolate",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-lindt-excellence-100",
      "retailer": "Tesco",
      "product": "Lindt Excellence Dark Chocolate 70% Cocoa",
      "pack": "100g",
      "price": 3.5,
      "category": "Treats",
      "source": "https://www.tesco.com/shop/en-GB/search?query=dark+chocolate",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-warburtons-wholemeal-800",
      "retailer": "Tesco",
      "product": "Warburtons Wholemeal Medium Sliced Bread",
      "pack": "800g",
      "price": 1.35,
      "category": "Bakery",
      "source": "https://www.tesco.com/shop/en-GB/search?query=bread+800g",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-warburtons-farmhouse-800",
      "retailer": "Tesco",
      "product": "Warburtons Farmhouse Thick Sliced White Bread",
      "pack": "800g",
      "price": 1.65,
      "category": "Bakery",
      "source": "https://www.tesco.com/shop/en-GB/search?query=bread+800g",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-hovis-soft-white-800",
      "retailer": "Tesco",
      "product": "Hovis Soft White Medium Sliced Bread",
      "pack": "800g",
      "price": 1.25,
      "category": "Bakery",
      "source": "https://www.tesco.com/shop/en-GB/search?query=bread+800g",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-multiseed-800",
      "retailer": "Tesco",
      "product": "Tesco Multiseed Batch Medium Sliced White Loaf",
      "pack": "800g",
      "price": 1.3,
      "category": "Bakery",
      "source": "https://www.tesco.com/shop/en-GB/search?query=bread+800g",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-hovis-best-of-both-800",
      "retailer": "Tesco",
      "product": "Hovis Best of Both Medium Bread",
      "pack": "800g",
      "price": 1.15,
      "category": "Bakery",
      "source": "https://www.tesco.com/shop/en-GB/search?query=bread+800g",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-white-toastie-800",
      "retailer": "Tesco",
      "product": "Tesco White Toastie Bread Thick Sliced",
      "pack": "800g",
      "price": 0.75,
      "category": "Bakery",
      "source": "https://www.tesco.com/shop/en-GB/search?query=bread+800g",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-hovis-seed-sensations-800",
      "retailer": "Tesco",
      "product": "Hovis Seed Sensations Seven Seeds Sliced Bread",
      "pack": "800g",
      "price": 2,
      "category": "Bakery",
      "source": "https://www.tesco.com/shop/en-GB/search?query=bread+800g",
      "verified": "2026-09-01",
      "loyaltyCard": "Tesco Clubcard",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.75,
      "hasLoyaltyPrice": true
    },
    {
      "id": "tesco-warburtons-toastie-800",
      "retailer": "Tesco",
      "product": "Warburtons Toastie Thick Sliced White Bread",
      "pack": "800g",
      "price": 1.4,
      "category": "Bakery",
      "source": "https://www.tesco.com/shop/en-GB/search?query=bread+800g",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-hovis-wholemeal-thick-800",
      "retailer": "Tesco",
      "product": "Hovis Wholemeal Thick Sliced Bread",
      "pack": "800g",
      "price": 1.5,
      "category": "Bakery",
      "source": "https://www.tesco.com/shop/en-GB/search?query=bread+800g",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-hovis-soft-white-thick-800",
      "retailer": "Tesco",
      "product": "Hovis Soft White Thick Sliced Bread",
      "pack": "800g",
      "price": 1.25,
      "category": "Bakery",
      "source": "https://www.tesco.com/shop/en-GB/search?query=bread+800g",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-finest-super-seeded-800",
      "retailer": "Tesco",
      "product": "Tesco Finest Super Seeded Sliced Farmhouse Loaf",
      "pack": "800g",
      "price": 1.75,
      "category": "Bakery",
      "source": "https://www.tesco.com/shop/en-GB/search?query=bread+800g",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-warburtons-seeded-800",
      "retailer": "Tesco",
      "product": "Warburtons Farmhouse Seeded Blend of 8 Seeds",
      "pack": "800g",
      "price": 2,
      "category": "Bakery",
      "source": "https://www.tesco.com/shop/en-GB/search?query=bread+800g",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "tesco-hovis-wholemeal-tasty-800",
      "retailer": "Tesco",
      "product": "Hovis Wholemeal Tasty Medium Bread",
      "pack": "800g",
      "price": 1.5,
      "category": "Bakery",
      "source": "https://www.tesco.com/shop/en-GB/search?query=bread+800g",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "sains-walkers-roast-chicken-6",
      "retailer": "Sainsbury's",
      "product": "Walkers Roast Chicken Multipack Crisps",
      "pack": "6 x 25g",
      "price": 2.2,
      "category": "Snacks",
      "source": "https://www.sainsburys.co.uk/groceries/browse/snacks-sweets-and-treats/crisps/c:1019694",
      "verified": "2026-09-01",
      "loyaltyCard": "Nectar",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.5,
      "hasLoyaltyPrice": true
    },
    {
      "id": "sains-walkers-ready-salted-6",
      "retailer": "Sainsbury's",
      "product": "Walkers Ready Salted Multipack Crisps",
      "pack": "6 x 25g",
      "price": 2.2,
      "category": "Snacks",
      "source": "https://www.sainsburys.co.uk/groceries/browse/snacks-sweets-and-treats/crisps/c:1019694",
      "verified": "2026-09-01",
      "loyaltyCard": "Nectar",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.5,
      "hasLoyaltyPrice": true
    },
    {
      "id": "sains-walkers-cheese-onion-6",
      "retailer": "Sainsbury's",
      "product": "Walkers Cheese & Onion Multipack Crisps",
      "pack": "6 x 25g",
      "price": 2.2,
      "category": "Snacks",
      "source": "https://www.sainsburys.co.uk/groceries/browse/snacks-sweets-and-treats/crisps/c:1019694",
      "verified": "2026-09-01",
      "loyaltyCard": "Nectar",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.5,
      "hasLoyaltyPrice": true
    },
    {
      "id": "sains-walkers-salt-vinegar-6",
      "retailer": "Sainsbury's",
      "product": "Walkers Salt & Vinegar Multipack Crisps",
      "pack": "6 x 25g",
      "price": 2.2,
      "category": "Snacks",
      "source": "https://www.sainsburys.co.uk/groceries/browse/snacks-sweets-and-treats/crisps/c:1019694",
      "verified": "2026-09-01",
      "loyaltyCard": "Nectar",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.5,
      "hasLoyaltyPrice": true
    },
    {
      "id": "sains-hula-hoops-bbq-6",
      "retailer": "Sainsbury's",
      "product": "Hula Hoops BBQ Beef Potato Ring Crisps",
      "pack": "6 x 24g",
      "price": 2.35,
      "category": "Snacks",
      "source": "https://www.sainsburys.co.uk/groceries/browse/snacks-sweets-and-treats/crisps/c:1019694",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "sains-own-cheese-onion-6",
      "retailer": "Sainsbury's",
      "product": "Sainsbury's Cheese & Onion Multipack Crisps",
      "pack": "6 x 25g",
      "price": 0.85,
      "category": "Snacks",
      "source": "https://www.sainsburys.co.uk/groceries/browse/snacks-sweets-and-treats/crisps/c:1019694",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "sains-pringles-sour-165",
      "retailer": "Sainsbury's",
      "product": "Pringles Sour Cream & Onion Sharing Crisps",
      "pack": "165g",
      "price": 2.5,
      "category": "Snacks",
      "source": "https://www.sainsburys.co.uk/groceries/browse/snacks-sweets-and-treats/crisps/c:1019694",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "sains-heinz-beans-richmond-200",
      "retailer": "Sainsbury's",
      "product": "Heinz Baked Beans & Richmond Pork Sausages",
      "pack": "200g",
      "price": 1.4,
      "category": "Tinned",
      "source": "https://www.sainsburys.co.uk/webapp/wcs/stores/servlet/gb/groceries/baked-beans",
      "verified": "2026-09-01",
      "loyaltyCard": "Nectar",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.2,
      "hasLoyaltyPrice": true
    },
    {
      "id": "sains-heinz-beans-4x415",
      "retailer": "Sainsbury's",
      "product": "Heinz Baked Beans in a Rich Tomato Sauce",
      "pack": "4 x 415g",
      "price": 3.9,
      "category": "Tinned",
      "source": "https://www.sainsburys.co.uk/webapp/wcs/stores/servlet/gb/groceries/baked-beans",
      "verified": "2026-09-01",
      "loyaltyCard": "Nectar",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 3,
      "hasLoyaltyPrice": true
    },
    {
      "id": "sains-cadbury-fingers-114",
      "retailer": "Sainsbury's",
      "product": "Cadbury Dairy Milk Fingers Milk Chocolate Covered Biscuits",
      "pack": "114g",
      "price": 2.25,
      "category": "Treats",
      "source": "https://sainsburys.co.uk/gol-ui/brands/cadbury/",
      "verified": "2026-09-01",
      "loyaltyCard": "Nectar",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.25,
      "hasLoyaltyPrice": true
    },
    {
      "id": "sains-cadbury-mini-fingers",
      "retailer": "Sainsbury's",
      "product": "Cadbury Mini Fingers Multipack",
      "pack": "5 x 19.3g",
      "price": 1.5,
      "category": "Treats",
      "source": "https://sainsburys.co.uk/gol-ui/brands/cadbury/",
      "verified": "2026-09-01",
      "loyaltyCard": "Nectar",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.25,
      "hasLoyaltyPrice": true
    },
    {
      "id": "sains-cadbury-animals",
      "retailer": "Sainsbury's",
      "product": "Cadbury Animals Mini Biscuits Multipack",
      "pack": "5 x 19.9g",
      "price": 1.5,
      "category": "Treats",
      "source": "https://sainsburys.co.uk/gol-ui/brands/cadbury/",
      "verified": "2026-09-01",
      "loyaltyCard": "Nectar",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.25,
      "hasLoyaltyPrice": true
    },
    {
      "id": "sains-cadbury-timeout",
      "retailer": "Sainsbury's",
      "product": "Cadbury Timeout Roundie Multipack Wafers",
      "pack": "5 x 30g",
      "price": 2,
      "category": "Treats",
      "source": "https://sainsburys.co.uk/gol-ui/brands/cadbury/",
      "verified": "2026-09-01",
      "loyaltyCard": "Nectar",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.5,
      "hasLoyaltyPrice": true
    },
    {
      "id": "sains-cadbury-mousse",
      "retailer": "Sainsbury's",
      "product": "Cadbury Dairy Milk Mousse",
      "pack": "4 x 45g",
      "price": 2,
      "category": "Chilled",
      "source": "https://sainsburys.co.uk/gol-ui/brands/cadbury/",
      "verified": "2026-09-01",
      "loyaltyCard": "Nectar",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.5,
      "hasLoyaltyPrice": true
    },
    {
      "id": "sains-cadbury-chunks-75",
      "retailer": "Sainsbury's",
      "product": "Cadbury Dairy Milk Chunks Dessert",
      "pack": "75g",
      "price": 1.25,
      "category": "Chilled",
      "source": "https://sainsburys.co.uk/gol-ui/brands/cadbury/",
      "verified": "2026-09-01",
      "loyaltyCard": "Nectar",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 0.9,
      "hasLoyaltyPrice": true
    },
    {
      "id": "sains-cadbury-cream-dessert",
      "retailer": "Sainsbury's",
      "product": "Cadbury Dairy Milk Creamy Milk & White Chocolate Dessert",
      "pack": "80g",
      "price": 1.5,
      "category": "Chilled",
      "source": "https://sainsburys.co.uk/gol-ui/brands/cadbury/",
      "verified": "2026-09-01",
      "loyaltyCard": "Nectar",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1,
      "hasLoyaltyPrice": true
    },
    {
      "id": "sains-diet-coke-24",
      "retailer": "Sainsbury's",
      "product": "Diet Coke Cola",
      "pack": "24 x 330ml",
      "price": 12,
      "category": "Drinks",
      "source": "https://sainsburys.co.uk/gol-ui/brands/coca-cola/facet%3Acocacola",
      "verified": "2026-09-01",
      "loyaltyCard": "Nectar",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 8.5,
      "hasLoyaltyPrice": true
    },
    {
      "id": "sains-coke-zero-24",
      "retailer": "Sainsbury's",
      "product": "Coca-Cola Zero Sugar",
      "pack": "24 x 330ml",
      "price": 12,
      "category": "Drinks",
      "source": "https://sainsburys.co.uk/gol-ui/brands/coca-cola/facet%3Acocacola",
      "verified": "2026-09-01",
      "loyaltyCard": "Nectar",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 8.5,
      "hasLoyaltyPrice": true
    },
    {
      "id": "sains-diet-coke-6x200",
      "retailer": "Sainsbury's",
      "product": "Diet Coke Cola",
      "pack": "6 x 200ml",
      "price": 3.5,
      "category": "Drinks",
      "source": "https://sainsburys.co.uk/gol-ui/brands/coca-cola/facet%3Acocacola",
      "verified": "2026-09-01",
      "loyaltyCard": "Nectar",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 2.5,
      "hasLoyaltyPrice": true
    },
    {
      "id": "sains-coke-zero-8",
      "retailer": "Sainsbury's",
      "product": "Coca-Cola Zero Sugar",
      "pack": "8 x 330ml",
      "price": 5.25,
      "category": "Drinks",
      "source": "https://sainsburys.co.uk/gol-ui/brands/coca-cola/facet%3Acocacola",
      "verified": "2026-09-01",
      "loyaltyCard": "Nectar",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 3.5,
      "hasLoyaltyPrice": true
    },
    {
      "id": "sains-monster-ultra-4",
      "retailer": "Sainsbury's",
      "product": "Monster Energy Drink Ultra",
      "pack": "4 x 500ml",
      "price": 6.4,
      "category": "Drinks",
      "source": "https://sainsburys.co.uk/gol-ui/brands/coca-cola/facet%3Acocacola",
      "verified": "2026-09-01",
      "loyaltyCard": "Nectar",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 5.2,
      "hasLoyaltyPrice": true
    },
    {
      "id": "sains-coke-zero-2l",
      "retailer": "Sainsbury's",
      "product": "Coca-Cola Zero Sugar",
      "pack": "2L",
      "price": 2.45,
      "category": "Drinks",
      "source": "https://sainsburys.co.uk/gol-ui/brands/coca-cola/facet%3Acocacola",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "coop-milk-1pint",
      "retailer": "Co-op",
      "product": "Co-op 1 Pint Fresh Semi-skimmed Milk",
      "pack": "568ml",
      "price": 0.95,
      "category": "Dairy",
      "source": "https://www.coop.co.uk/products/aldi-price-match",
      "verified": "2026-09-01",
      "loyaltyCard": "Co-op Member Card",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 0.85,
      "hasLoyaltyPrice": true
    },
    {
      "id": "coop-milk-4pint",
      "retailer": "Co-op",
      "product": "Co-op 4 Pint Fresh Semi-skimmed Milk",
      "pack": "2.27L",
      "price": 1.95,
      "category": "Dairy",
      "source": "https://www.coop.co.uk/products/aldi-price-match",
      "verified": "2026-09-01",
      "loyaltyCard": "Co-op Member Card",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.65,
      "hasLoyaltyPrice": true
    },
    {
      "id": "coop-cheddar-400",
      "retailer": "Co-op",
      "product": "Co-op British Mature White Cheddar",
      "pack": "400g",
      "price": 3.5,
      "category": "Chilled",
      "source": "https://www.coop.co.uk/products/aldi-price-match",
      "verified": "2026-09-01",
      "loyaltyCard": "Co-op Member Card",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 2.49,
      "hasLoyaltyPrice": true
    },
    {
      "id": "coop-buttery-500",
      "retailer": "Co-op",
      "product": "Co-op Buttery",
      "pack": "500g",
      "price": 1.6,
      "category": "Dairy",
      "source": "https://www.coop.co.uk/products/aldi-price-match",
      "verified": "2026-09-01",
      "loyaltyCard": "Co-op Member Card",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 0.89,
      "hasLoyaltyPrice": true
    },
    {
      "id": "coop-eggs-medium-6",
      "retailer": "Co-op",
      "product": "Co-op British Medium Free Range Eggs",
      "pack": "6 pack",
      "price": 2,
      "category": "Dairy",
      "source": "https://www.coop.co.uk/products/aldi-price-match/milk-butter-cheese-eggs",
      "verified": "2026-09-01",
      "loyaltyCard": "Co-op Member Card",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.55,
      "hasLoyaltyPrice": true
    },
    {
      "id": "coop-eggs-large-6",
      "retailer": "Co-op",
      "product": "Co-op British Large Free Range Eggs",
      "pack": "6 pack",
      "price": 2.2,
      "category": "Dairy",
      "source": "https://www.coop.co.uk/products/aldi-price-match/milk-butter-cheese-eggs",
      "verified": "2026-09-01",
      "loyaltyCard": "Co-op Member Card",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.79,
      "hasLoyaltyPrice": true
    },
    {
      "id": "coop-yogurt-greek-500",
      "retailer": "Co-op",
      "product": "Co-op Greek Style Natural Yogurt",
      "pack": "500g",
      "price": 1.25,
      "category": "Chilled",
      "source": "https://www.coop.co.uk/products/aldi-price-match/milk-butter-cheese-eggs",
      "verified": "2026-09-01",
      "loyaltyCard": "Co-op Member Card",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 0.95,
      "hasLoyaltyPrice": true
    },
    {
      "id": "coop-linguine-500",
      "retailer": "Co-op",
      "product": "Co-op Linguine Pasta",
      "pack": "500g",
      "price": 0.85,
      "category": "Food cupboard",
      "source": "https://www.coop.co.uk/products/co-op-linguine-pasta-500g",
      "verified": "2026-09-01",
      "loyaltyCard": "Co-op Member Card",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 0.75,
      "hasLoyaltyPrice": true
    },
    {
      "id": "coop-fusilli-500",
      "retailer": "Co-op",
      "product": "Co-op Fusilli Pasta Twists",
      "pack": "500g",
      "price": 0.85,
      "category": "Food cupboard",
      "source": "https://www.coop.co.uk/products/co-op-fusilli-pasta-twists-500g",
      "verified": "2026-09-01",
      "loyaltyCard": "Co-op Member Card",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 0.69,
      "hasLoyaltyPrice": true
    },
    {
      "id": "coop-macaroni-500",
      "retailer": "Co-op",
      "product": "Co-op Italian Menu Macaroni",
      "pack": "500g",
      "price": 0.85,
      "category": "Food cupboard",
      "source": "https://www.coop.co.uk/products/aldi-price-match",
      "verified": "2026-09-01",
      "loyaltyCard": "Co-op Member Card",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 0.72,
      "hasLoyaltyPrice": true
    },
    {
      "id": "coop-farfalle-500",
      "retailer": "Co-op",
      "product": "Co-op Italian Menu Farfalle",
      "pack": "500g",
      "price": 0.85,
      "category": "Food cupboard",
      "source": "https://www.coop.co.uk/products/aldi-price-match",
      "verified": "2026-09-01",
      "loyaltyCard": "Co-op Member Card",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 0.69,
      "hasLoyaltyPrice": true
    },
    {
      "id": "coop-tagliatelle-500",
      "retailer": "Co-op",
      "product": "Co-op Italian Menu Tagliatelle",
      "pack": "500g",
      "price": 0.85,
      "category": "Food cupboard",
      "source": "https://www.coop.co.uk/products/aldi-price-match",
      "verified": "2026-09-01",
      "loyaltyCard": "Co-op Member Card",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 0.69,
      "hasLoyaltyPrice": true
    },
    {
      "id": "coop-spaghetti-500",
      "retailer": "Co-op",
      "product": "Co-op Spaghetti",
      "pack": "500g",
      "price": 0.85,
      "category": "Food cupboard",
      "source": "https://www.coop.co.uk/products/aldi-price-match",
      "verified": "2026-09-01",
      "loyaltyCard": "Co-op Member Card",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 0.75,
      "hasLoyaltyPrice": true
    },
    {
      "id": "coop-wholewheat-fusilli-500",
      "retailer": "Co-op",
      "product": "Co-op Italian Wholewheat Fusilli",
      "pack": "500g",
      "price": 0.85,
      "category": "Food cupboard",
      "source": "https://www.coop.co.uk/products/aldi-price-match",
      "verified": "2026-09-01",
      "loyaltyCard": "Co-op Member Card",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 0.75,
      "hasLoyaltyPrice": true
    },
    {
      "id": "coop-wholewheat-spaghetti-500",
      "retailer": "Co-op",
      "product": "Co-op Wholewheat Spaghetti",
      "pack": "500g",
      "price": 0.85,
      "category": "Food cupboard",
      "source": "https://www.coop.co.uk/products/aldi-price-match",
      "verified": "2026-09-01",
      "loyaltyCard": "Co-op Member Card",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 0.75,
      "hasLoyaltyPrice": true
    },
    {
      "id": "coop-rice-1kg",
      "retailer": "Co-op",
      "product": "Co-op Long Grain Rice",
      "pack": "1kg",
      "price": 1.55,
      "category": "Food cupboard",
      "source": "https://www.coop.co.uk/products/aldi-price-match",
      "verified": "2026-09-01",
      "loyaltyCard": "Co-op Member Card",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.25,
      "hasLoyaltyPrice": true
    },
    {
      "id": "coop-noodles-250",
      "retailer": "Co-op",
      "product": "Co-op Medium Egg Noodles",
      "pack": "250g",
      "price": 1.25,
      "category": "Food cupboard",
      "source": "https://www.coop.co.uk/products/aldi-price-match",
      "verified": "2026-09-01",
      "loyaltyCard": "Co-op Member Card",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 0.95,
      "hasLoyaltyPrice": true
    },
    {
      "id": "coop-malt-biscuits-250",
      "retailer": "Co-op",
      "product": "Co-op Milk Chocolate Malted Milk Biscuits",
      "pack": "250g",
      "price": 1.5,
      "category": "Treats",
      "source": "https://www.coop.co.uk/products/aldi-price-match",
      "verified": "2026-09-01",
      "loyaltyCard": "Co-op Member Card",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.29,
      "hasLoyaltyPrice": true
    },
    {
      "id": "coop-ketchup-550",
      "retailer": "Co-op",
      "product": "Co-op Tomato Ketchup",
      "pack": "550g",
      "price": 1,
      "category": "Food cupboard",
      "source": "https://www.coop.co.uk/products/aldi-price-match",
      "verified": "2026-09-01",
      "loyaltyCard": "Co-op Member Card",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 0.89,
      "hasLoyaltyPrice": true
    },
    {
      "id": "coop-chopped-tomatoes-400",
      "retailer": "Co-op",
      "product": "Co-op Chopped Tomatoes",
      "pack": "400g",
      "price": 0.5,
      "category": "Food cupboard",
      "source": "https://www.coop.co.uk/products/aldi-price-match",
      "verified": "2026-09-01",
      "loyaltyCard": "Co-op Member Card",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 0.47,
      "hasLoyaltyPrice": true
    },
    {
      "id": "coop-flour-15kg",
      "retailer": "Co-op",
      "product": "Co-op Plain White Flour",
      "pack": "1.5kg",
      "price": 0.85,
      "category": "Baking",
      "source": "https://www.coop.co.uk/products/aldi-price-match",
      "verified": "2026-09-01",
      "loyaltyCard": "Co-op Member Card",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 0.7,
      "hasLoyaltyPrice": true
    },
    {
      "id": "coop-veg-oil-1l",
      "retailer": "Co-op",
      "product": "Co-op Pure Vegetable Oil",
      "pack": "1L",
      "price": 1.65,
      "category": "Food cupboard",
      "source": "https://www.coop.co.uk/products/aldi-price-match",
      "verified": "2026-09-01",
      "loyaltyCard": "Co-op Member Card",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.45,
      "hasLoyaltyPrice": true
    },
    {
      "id": "iceland-eggs-10-large",
      "retailer": "Iceland",
      "product": "Iceland 10 Large Class A British Eggs",
      "pack": "10 pack",
      "price": 2.2,
      "category": "Dairy",
      "source": "https://www.iceland.co.uk/fresh/milk-butter-and-eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "iceland-semi-2l",
      "retailer": "Iceland",
      "product": "Iceland British Semi-Skimmed Milk",
      "pack": "2L",
      "price": 1.65,
      "category": "Dairy",
      "source": "https://www.iceland.co.uk/fresh/milk-butter-and-eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "iceland-whole-2l",
      "retailer": "Iceland",
      "product": "Iceland British Whole Milk",
      "pack": "2L",
      "price": 1.65,
      "category": "Dairy",
      "source": "https://www.iceland.co.uk/fresh/milk-butter-and-eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "iceland-lurpak-400",
      "retailer": "Iceland",
      "product": "Lurpak Slightly Salted Spreadable Blend of Butter and Rapeseed Oil",
      "pack": "400g",
      "price": 4.25,
      "category": "Dairy",
      "source": "https://www.iceland.co.uk/fresh/milk-butter-and-eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "iceland-eggs-10-mixed",
      "retailer": "Iceland",
      "product": "Iceland 10 Mixed Weight British Eggs",
      "pack": "10 pack",
      "price": 1.9,
      "category": "Dairy",
      "source": "https://www.iceland.co.uk/fresh/milk-butter-and-eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "iceland-butter-250",
      "retailer": "Iceland",
      "product": "Iceland British Salted Butter",
      "pack": "250g",
      "price": 2,
      "category": "Dairy",
      "source": "https://www.iceland.co.uk/fresh/milk-butter-and-eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "iceland-eggs-6-large",
      "retailer": "Iceland",
      "product": "Iceland 6 Large Free Range British Eggs",
      "pack": "6 pack",
      "price": 2,
      "category": "Dairy",
      "source": "https://www.iceland.co.uk/fresh/milk-butter-and-eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "iceland-elmlea",
      "retailer": "Iceland",
      "product": "Elmlea Double Cream Alternative",
      "pack": "270ml",
      "price": 1.65,
      "category": "Dairy",
      "source": "https://www.iceland.co.uk/fresh/milk-butter-and-eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "iceland-semi-1l",
      "retailer": "Iceland",
      "product": "Iceland British Semi-Skimmed Milk",
      "pack": "1L",
      "price": 1.2,
      "category": "Dairy",
      "source": "https://www.iceland.co.uk/fresh/milk-butter-and-eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "iceland-double-cream-300",
      "retailer": "Iceland",
      "product": "Iceland British Double Cream",
      "pack": "300ml",
      "price": 1.95,
      "category": "Dairy",
      "source": "https://www.iceland.co.uk/fresh/milk-butter-and-eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "iceland-anchor-salted-200",
      "retailer": "Iceland",
      "product": "Anchor Salted Butter",
      "pack": "200g",
      "price": 2.6,
      "category": "Dairy",
      "source": "https://www.iceland.co.uk/fresh/milk-butter-and-eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "iceland-cravendale-whole-2l",
      "retailer": "Iceland",
      "product": "Arla Cravendale Filtered Fresh Whole Milk",
      "pack": "2L",
      "price": 2.75,
      "category": "Dairy",
      "source": "https://www.iceland.co.uk/fresh/milk-butter-and-eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "iceland-flora-buttery-450",
      "retailer": "Iceland",
      "product": "Flora Buttery Butter Alternative",
      "pack": "450g",
      "price": 1.9,
      "category": "Dairy",
      "source": "https://www.iceland.co.uk/fresh/milk-butter-and-eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "iceland-eggs-30",
      "retailer": "Iceland",
      "product": "Iceland 30 Mixed Size Eggs",
      "pack": "30 pack",
      "price": 4.25,
      "category": "Dairy",
      "source": "https://www.iceland.co.uk/fresh/milk-butter-and-eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "iceland-dairypak-500",
      "retailer": "Iceland",
      "product": "Dairypak Irish Butter Blended with Vegetable Oil",
      "pack": "500g",
      "price": 2.25,
      "category": "Dairy",
      "source": "https://www.iceland.co.uk/fresh/milk-butter-and-eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "iceland-scottish-semi-2l",
      "retailer": "Iceland",
      "product": "Iceland Scottish Semi-Skimmed Milk",
      "pack": "2L",
      "price": 1.65,
      "category": "Dairy",
      "source": "https://www.iceland.co.uk/fresh/milk-butter-and-eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "iceland-lard-250",
      "retailer": "Iceland",
      "product": "Meadow Churn Lard",
      "pack": "250g",
      "price": 0.65,
      "category": "Cooking",
      "source": "https://www.iceland.co.uk/fresh/milk-butter-and-eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "iceland-actimel-8",
      "retailer": "Iceland",
      "product": "Actimel Strawberry Immune Support Yoghurt Drink Multipack",
      "pack": "8 x 100g",
      "price": 3.75,
      "category": "Chilled",
      "source": "https://www.iceland.co.uk/fresh/milk-butter-and-eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "iceland-moo-milk-1l",
      "retailer": "Iceland",
      "product": "Moo Milk Strawberry Flavour British Milk",
      "pack": "1L",
      "price": 1.5,
      "category": "Dairy",
      "source": "https://www.iceland.co.uk/fresh/milk-butter-and-eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "iceland-viva-longlife-1l",
      "retailer": "Iceland",
      "product": "Viva Semi-Skimmed Long-Life Milk",
      "pack": "1L",
      "price": 1.3,
      "category": "Dairy",
      "source": "https://www.iceland.co.uk/fresh/milk-butter-and-eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "iceland-cream-300",
      "retailer": "Iceland",
      "product": "Iceland Sweetened Squirty Cream",
      "pack": "250g",
      "price": 1.85,
      "category": "Dairy",
      "source": "https://www.iceland.co.uk/fresh/milk-butter-and-eggs",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "lidl-shortcake-dark",
      "retailer": "Lidl",
      "product": "ITALIAMO Shortcake Biscuits with Dark Chocolate",
      "pack": "not stated",
      "price": 1.99,
      "category": "Treats",
      "source": "https://lt.lidl.com/h/confectionery-snacks/h10096205",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "lidl-cocoa-cream-shortcake",
      "retailer": "Lidl",
      "product": "ITALIAMO Cocoa & Cream Shortcake Biscuits",
      "pack": "not stated",
      "price": 1.99,
      "category": "Treats",
      "source": "https://lt.lidl.com/h/confectionery-snacks/h10096205",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "lidl-sponge-milk-filling",
      "retailer": "Lidl",
      "product": "ITALIAMO Sponge Cakes with Milk Flavoured Filling",
      "pack": "not stated",
      "price": 1.49,
      "category": "Bakery",
      "source": "https://lt.lidl.com/h/confectionery-snacks/h10096205",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    },
    {
      "id": "lidl-sponge-fingers",
      "retailer": "Lidl",
      "product": "ITALIAMO Sponge Fingers",
      "pack": "not stated",
      "price": 2.49,
      "category": "Bakery",
      "source": "https://lt.lidl.com/h/confectionery-snacks/h10096205",
      "verified": "2026-08-26",
      "loyaltyCard": "Lidl Plus",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.99,
      "hasLoyaltyPrice": true
    },
    {
      "id": "lidl-tarallini",
      "retailer": "Lidl",
      "product": "ITALIAMO Tarallini Snacks Assorted",
      "pack": "not stated",
      "price": 2.79,
      "category": "Snacks",
      "source": "https://lt.lidl.com/h/confectionery-snacks/h10096205",
      "verified": "2026-08-26",
      "loyaltyCard": "Lidl Plus",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.99,
      "hasLoyaltyPrice": true
    },
    {
      "id": "lidl-crostatine",
      "retailer": "Lidl",
      "product": "ITALIAMO Crostatine Tartlets with Hazelnut and Cocoa Filling",
      "pack": "not stated",
      "price": 1.49,
      "category": "Treats",
      "source": "https://lt.lidl.com/h/confectionery-snacks/h10096205",
      "verified": "2026-08-26",
      "loyaltyCard": "Lidl Plus",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 0.99,
      "hasLoyaltyPrice": true
    },
    {
      "id": "lidl-tortilla-chips",
      "retailer": "Lidl",
      "product": "DELUXE Premium Tortilla Chips Assorted",
      "pack": "not stated",
      "price": 1.19,
      "category": "Snacks",
      "source": "https://lt.lidl.com/h/confectionery-snacks/h10096205",
      "verified": "2026-08-26",
      "loyaltyCard": "Lidl Plus",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 0.95,
      "hasLoyaltyPrice": true
    },
    {
      "id": "lidl-curlies",
      "retailer": "Lidl",
      "product": "HARVEST BASKET Curlies",
      "pack": "not stated",
      "price": 1.59,
      "category": "Snacks",
      "source": "https://lt.lidl.com/h/confectionery-snacks/h10096205",
      "verified": "2026-08-26",
      "loyaltyCard": "Lidl Plus",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.29,
      "hasLoyaltyPrice": true
    },
    {
      "id": "lidl-cucumber",
      "retailer": "Lidl",
      "product": "Cucumber",
      "pack": "1 each",
      "price": 0.99,
      "category": "Fruit & veg",
      "source": "https://shopslinks.co.uk/compare/cucumber",
      "verified": "2026-09-01",
      "loyaltyCard": "Lidl Plus",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 0.79,
      "hasLoyaltyPrice": true
    },
    {
      "id": "lidl-red-pepper",
      "retailer": "Lidl",
      "product": "Loose Red Pepper",
      "pack": "1 each",
      "price": 0.7,
      "category": "Fruit & veg",
      "source": "https://shopslinks.co.uk/compare/loose-red-pepper",
      "verified": "2026-09-01",
      "loyaltyCard": "Lidl Plus",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 0.49,
      "hasLoyaltyPrice": true
    },
    {
      "id": "lidl-olives",
      "retailer": "Lidl",
      "product": "Eridanous Whole Kalamon Olives",
      "pack": "not stated",
      "price": 2.79,
      "category": "Food cupboard",
      "source": "https://shopslinks.co.uk/compare/eridanous-whole-kalamon-olives",
      "verified": "2026-09-01",
      "loyaltyCard": "Lidl Plus",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 2.29,
      "hasLoyaltyPrice": true
    },
    {
      "id": "lidl-olive-spread",
      "retailer": "Lidl",
      "product": "Eridanous Olive Spread",
      "pack": "not stated",
      "price": 1.99,
      "category": "Food cupboard",
      "source": "https://shopslinks.co.uk/compare/eridanous-olive-spread",
      "verified": "2026-09-01",
      "loyaltyCard": "Lidl Plus",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.49,
      "hasLoyaltyPrice": true
    },
    {
      "id": "lidl-tahini",
      "retailer": "Lidl",
      "product": "Eridanous Tahini Assorted",
      "pack": "not stated",
      "price": 2.49,
      "category": "Food cupboard",
      "source": "https://shopslinks.co.uk/compare/eridanous-tahini-assorted",
      "verified": "2026-09-01",
      "loyaltyCard": "Lidl Plus",
      "priceType": "standard_and_loyalty",
      "loyaltyPrice": 1.99,
      "hasLoyaltyPrice": true
    },
    {
      "id": "lidl-oat-milk",
      "retailer": "Lidl",
      "product": "Choccorrific Oat Milk",
      "pack": "1L",
      "price": 1.99,
      "category": "Drinks",
      "source": "https://shopslinks.co.uk/compare/choccorrific-oat-milk-1l",
      "verified": "2026-09-01",
      "priceType": "standard",
      "hasLoyaltyPrice": false
    }
  ]
};
